import type { MetadataRoute } from 'next'

import { blogPosts } from '@/lib/blog-data'

export const dynamic = 'force-static'

const BASE_URL = 'https://www.trailofchina.com'
const defaultLastModified = new Date()

type SitemapEntry = {
  path: string
  changeFrequency: NonNullable<MetadataRoute.Sitemap[number]['changeFrequency']>
  priority: number
  lastModified?: Date
}

const createEntry = ({
  path,
  changeFrequency,
  priority,
  lastModified = defaultLastModified,
}: SitemapEntry): MetadataRoute.Sitemap[number] => ({
  url: `${BASE_URL}${path}`,
  lastModified,
  changeFrequency,
  priority,
})

const staticRoutes: SitemapEntry[] = [
  { path: '/', changeFrequency: 'weekly', priority: 1.0 },
  { path: '/about', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/china-basics', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/alipay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/communication', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/didi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/maps', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/meituan', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/payment', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/travel', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/trip-com', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/vpn', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/what-apps-to-use/wechat-pay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-internet', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-internet/esim', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-internet/airalo-esim', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-internet/holafly-esim', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-internet/physical-sim', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs/censorship', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs/cultural-differences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs/passport-rules', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs/security-standards', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-china-differs/visa-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/12306', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/bicycle', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/bus', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/car', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/city-to-city', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/didi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/metro-subway', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/plane', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/taxi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/how-to-get-around/train', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/before-you-go', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/before-you-go/is-china-safe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/china-basics/before-you-go/packing-list', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/destinations/shanghai/local-experiences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/local-tips', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/bund', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/french-concession', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/jade-buddha-temple', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/shanghai-tower', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/tianzifang', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/what-to-do/yu-garden', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat/hairy-crab', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat/red-braised-pork', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat/scallion-oil-noodles', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat/shengjianbao', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-eat/xiaolongbao', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-stay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-stay/bund-area', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-stay/french-concession', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-stay/jingan', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/shanghai/where-to-stay/xintiandi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/local-experiences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/local-tips', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/798-art-district', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/forbidden-city', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/great-wall', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/hutong', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/lama-temple', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/summer-palace', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/what-to-do/temple-of-heaven', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/baodu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/jianbing', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/lamb-skewers', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/peking-duck', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/tanghulu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-eat/zhajiangmian', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-stay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-stay/dongcheng-hutong', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-stay/haidian', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-stay/sanlitun', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/beijing/where-to-stay/wangfujing', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/local-experiences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/local-tips', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do/bell-drum-tower', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do/big-wild-goose-pagoda', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do/city-wall', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do/muslim-quarter', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/what-to-do/terracotta-warriors', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-eat', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-eat/biangbiang-noodles', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-eat/liangpi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-eat/roujiamo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-eat/yangroupaomo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-stay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-stay/bell-tower', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-stay/dayan-pagoda', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/xian/where-to-stay/muslim-quarter', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/local-experiences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/local-tips', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/jinli-ancient-street', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/kuanzhai-alley', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/panda-base', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/peoples-park-teahouse', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/sichuan-opera', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/what-to-do/wenshu-monastery', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-eat', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-eat/dan-dan-noodles', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-eat/kung-pao-chicken', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-eat/mapo-tofu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-eat/sichuan-hotpot', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-stay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-stay/chunxi-road', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-stay/jinli-area', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chengdu/where-to-stay/wide-narrow-alley', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/local-experiences', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/local-tips', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/ciqikou', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/eling-park', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/hongya-cave', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/liziba-monorail', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/three-gorges-museum', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/what-to-do/yangtze-cable-car', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-eat', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-eat/chongqing-hotpot', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-eat/grilled-fish', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-eat/xiaomian', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-stay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-stay/cuntan', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-stay/hongyadong-area', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/destinations/chongqing/where-to-stay/jiefangbei', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/plan-your-trip', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/plan-your-trip/best-time-to-visit', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/budget', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/preplanned-trips', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/preplanned-trips/7-day-route', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/preplanned-trips/10-day-route', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/preplanned-trips/14-day-route', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/plan-your-trip/travel-planner', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/blog', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/imprint', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/privacy', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/cookie-policy', changeFrequency: 'yearly', priority: 0.3 },
]

export default function sitemap(): MetadataRoute.Sitemap {
  const blogRoutes: MetadataRoute.Sitemap = blogPosts.map((post) =>
    createEntry({
      path: `/blog/${post.slug}`,
      changeFrequency: 'weekly',
      priority: 0.7,
      lastModified: new Date(post.date),
    })
  )

  return [...staticRoutes.map(createEntry), ...blogRoutes]
}
