import {
  Calendar,
  Car,
  CloudRain,
  CreditCard,
  Lightbulb,
  Map,
  Moon,
  ShieldCheck,
  Smartphone,
  Sun,
  Sunrise,
  Sunset,
  Thermometer,
  TrainFront,
  Wifi,
} from "lucide-react";
import type { CityHubConfig } from "../../../components/CityHubTemplate/types";
import {
  shanghaiBoundary,
  shanghaiMaxBounds,
} from "./data/shanghai-boundary";
import { metroLines } from "./data/metro-lines";
import { markers, unifiedLocations } from "./data/attractions";
import { transportHubs } from "./data/transport-hubs";

export const shanghaiConfig: CityHubConfig = {
  slug: "shanghai",
  nameEn: "Shanghai",
  nameZh: "上海",
  tagline: "Colonial elegance meets tomorrow's skyline",
  watermark: "上海",
  searchPlaceholder: 'Filter Shanghai... (e.g. "bund", "dumplings", "free")',
  mapCenter: [31.2304, 121.4737],
  mapZoom: 10,
  boundary: shanghaiBoundary,
  maxBounds: shanghaiMaxBounds,
  gallerySeeds: [
    "shanghai-bund",
    "shanghai-yugarden",
    "shanghai-frenchconcession",
    "shanghai-tower",
    "shanghai-tianzifang",
    "shanghai-jadebuddha",
    "shanghai-bund-night",
    "shanghai-nanjing-road",
    "shanghai-skyline",
    "shanghai-huangpu",
    "shanghai-lujiazui",
  ],
  galleryAlts: [
    "The Bund waterfront promenade with colonial-era buildings, Shanghai",
    "Yu Garden classical Chinese pavilions and rockery, Shanghai",
    "French Concession tree-lined streets with cafés and boutiques, Shanghai",
    "Shanghai Tower observation deck with panoramic city views",
    "Tianzifang narrow alley filled with art studios and craft shops, Shanghai",
    "Jade Buddha Temple with seated jade Buddha statue, Shanghai",
    "The Bund illuminated skyline reflecting on Huangpu River at night, Shanghai",
    "Nanjing Road bustling pedestrian shopping street, Shanghai",
    "Shanghai skyline with Oriental Pearl Tower and skyscrapers",
    "Huangpu River cruise boats passing the Bund, Shanghai",
    "Lujiazui financial district skyscrapers at dusk, Shanghai",
  ],
  pills: [
    { icon: Wifi, label: "Internet:", text: "VPN required" },
    { icon: CreditCard, label: "", text: "Cashless society" },
    { icon: TrainFront, label: "", text: "Excellent metro" },
    { icon: Thermometer, label: "Best:", text: "Mar–May, Sep–Nov" },
  ],
  metroLines,
  transportHubs,
  unifiedLocations,
  markers,
  attractionCards: [
    {
      id: "bund",
      name: "The Bund",
      lat: 31.24,
      lng: 121.49,
      imageSeed: "shanghai-bund",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do/bund",
          hook: "Shanghai's most iconic waterfront promenade with skyline views.",
          tag: "Free",
        },
      },
    },
    {
      id: "yu-garden",
      name: "Yu Garden",
      lat: 31.227,
      lng: 121.492,
      imageSeed: "shanghai-yugarden",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do/yu-garden",
          hook: "A 400-year-old classical garden surrounded by a lively bazaar.",
          tag: "¥40",
        },
      },
    },
    {
      id: "french-concession",
      name: "French Concession",
      lat: 31.21,
      lng: 121.46,
      imageSeed: "shanghai-frenchconcession",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do/french-concession",
          hook: "Tree-lined avenues, Art Deco villas, and charming cafés.",
          tag: "Free",
        },
      },
    },
    {
      id: "shanghai-tower",
      name: "Shanghai Tower",
      lat: 31.2355,
      lng: 121.5015,
      imageSeed: "shanghai-tower",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do/shanghai-tower",
          hook: "The world's second-tallest building with a jaw-dropping observation deck.",
          tag: "¥180",
        },
      },
    },
    {
      id: "tianzifang",
      name: "Tianzifang",
      lat: 31.203,
      lng: 121.468,
      imageSeed: "shanghai-tianzifang",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do",
          hook: "Winding alleyways packed with studios, galleries, and craft shops.",
          tag: "Free",
        },
      },
    },
    {
      id: "jade-buddha",
      name: "Jade Buddha Temple",
      lat: 31.223,
      lng: 121.442,
      imageSeed: "shanghai-jadebuddha",
      defaultCategory: "things-to-do",
      categories: {
        "things-to-do": {
          href: "/destinations/shanghai/what-to-do",
          hook: "Serene Buddhist temple housing two stunning white jade Buddhas.",
          tag: "¥20",
        },
      },
    },
  ],
  foodCards: [
    {
      id: "xiaolongbao",
      name: "Xiaolongbao",
      lat: 31.225,
      lng: 121.475,
      imageSeed: "xiaolongbao",
      defaultCategory: "where-to-eat",
      categories: {
        "where-to-eat": {
          href: "/destinations/shanghai/where-to-eat/xiaolongbao",
          hook: "Shanghai's iconic soup dumplings",
          tag: "Street Food · ¥30",
        },
      },
    },
    {
      id: "shengjianbao",
      name: "Shengjianbao",
      lat: 31.238,
      lng: 121.488,
      imageSeed: "shengjianbao",
      defaultCategory: "where-to-eat",
      categories: {
        "where-to-eat": {
          href: "/destinations/shanghai/where-to-eat/shengjianbao",
          hook: "Pan-fried buns with a crispy bottom",
          tag: "Street Food · ¥15",
        },
      },
    },
    {
      id: "hairy-crab",
      name: "Hairy Crab",
      lat: 31.215,
      lng: 121.49,
      imageSeed: "hairy-crab",
      defaultCategory: "where-to-eat",
      categories: {
        "where-to-eat": {
          href: "/destinations/shanghai/where-to-eat/hairy-crab",
          hook: "Autumn delicacy from nearby Yangcheng Lake",
          tag: "Seasonal · ¥200+",
        },
      },
    },
    {
      id: "scallion-oil-noodles",
      name: "Scallion Oil Noodles",
      lat: 31.232,
      lng: 121.455,
      imageSeed: "scallion-noodles",
      defaultCategory: "where-to-eat",
      categories: {
        "where-to-eat": {
          href: "/destinations/shanghai/where-to-eat/scallion-oil-noodles",
          hook: "Simple, fragrant, and deeply comforting",
          tag: "Restaurant · ¥25–40",
        },
      },
    },
  ],
  neighborhoodCards: [
    {
      id: "bund-area",
      name: "Bund Area",
      lat: 31.24,
      lng: 121.49,
      imageSeed: "shanghai-bund-area",
      defaultCategory: "where-to-stay",
      categories: {
        "where-to-stay": {
          href: "/destinations/shanghai/where-to-stay/bund-area",
          hook: "Iconic skyline · Historic architecture",
          tag: "",
        },
      },
    },
    {
      id: "french-concession-stay",
      name: "French Concession",
      lat: 31.21,
      lng: 121.46,
      imageSeed: "shanghai-french-concession-stay",
      defaultCategory: "where-to-stay",
      categories: {
        "where-to-stay": {
          href: "/destinations/shanghai/where-to-stay/french-concession",
          hook: "Cafés & boutiques · Tree-lined streets",
          tag: "",
        },
      },
    },
    {
      id: "jingan",
      name: "Jing'an",
      lat: 31.234,
      lng: 121.446,
      imageSeed: "shanghai-jingan",
      defaultCategory: "where-to-stay",
      categories: {
        "where-to-stay": {
          href: "/destinations/shanghai/where-to-stay/jingan",
          hook: "Local life · Metro hub",
          tag: "",
        },
      },
    },
    {
      id: "xintiandi",
      name: "Xintiandi",
      lat: 31.219,
      lng: 121.475,
      imageSeed: "shanghai-xintiandi",
      defaultCategory: "where-to-stay",
      categories: {
        "where-to-stay": {
          href: "/destinations/shanghai/where-to-stay/xintiandi",
          hook: "Modern luxury · Nightlife",
          tag: "",
        },
      },
    },
  ],
  localTips: [
    {
      id: "plum-rain",
      title: "Plum Rain Season",
      text: "June–July brings muggy, rainy weather. Clothes never dry. Pack extra socks and a travel umbrella.",
      icon: CloudRain,
      href: "/destinations/shanghai/local-tips",
    },
    {
      id: "taxi-pro-tip",
      title: "Taxi Pro Tip",
      text: "Shanghai taxis are cheap, but drivers rarely speak English. Use DiDi with English interface instead.",
      icon: Car,
      href: "/destinations/shanghai/local-tips",
    },
    {
      id: "bund-after-dark",
      title: "Bund After Dark",
      text: "The Bund is free and best at night. Skip the overpriced tourist tunnel — walk or take the metro instead.",
      icon: Moon,
      href: "/destinations/shanghai/local-tips",
    },
    {
      id: "metro-maps",
      title: "Metro & Maps",
      text: "Metro stops have English signs. Google Maps works with a VPN; Amap is the best local alternative.",
      icon: Map,
      href: "/destinations/shanghai/local-tips",
    },
  ],
  itinerary: [
    {
      dayTitle: "Day 1: The Classics",
      timeOfDay: "morning",
      items: [
        {
          name: "The Bund",
          href: "/destinations/shanghai/what-to-do/bund",
          time: "1–2h",
          cost: "Free",
          imageSeed: "shanghai-bund",
          desc: "Start at dawn for empty walkways and soft light on the skyline.",
        },
        {
          name: "Yu Garden",
          href: "/destinations/shanghai/what-to-do/yu-garden",
          time: "1–2h",
          cost: "¥40",
          imageSeed: "shanghai-yugarden",
          desc: "Ancient garden and bazaar. Go early before the crowds.",
        },
      ],
    },
    {
      dayTitle: "Day 1: The Classics",
      timeOfDay: "afternoon",
      items: [
        {
          name: "Xiaolongbao Lunch",
          href: "/destinations/shanghai/where-to-eat/xiaolongbao",
          time: "1h",
          cost: "¥30–60",
          imageSeed: "xiaolongbao",
          desc: "Hit a local spot near Yu Garden for Shanghai's famous soup dumplings.",
        },
        {
          name: "French Concession",
          href: "/destinations/shanghai/what-to-do/french-concession",
          time: "2–3h",
          cost: "Free",
          imageSeed: "shanghai-frenchconcession",
          desc: "Stroll tree-lined streets, browse boutiques, stop for coffee.",
        },
        {
          name: "Tianzifang",
          href: "/destinations/shanghai/what-to-do",
          time: "1–2h",
          cost: "Free",
          imageSeed: "shanghai-tianzifang",
          desc: "Artsy alleys with galleries and craft shops. Easy walk from French Concession.",
        },
      ],
    },
    {
      dayTitle: "Day 1: The Classics",
      timeOfDay: "evening",
      items: [
        {
          name: "Bund at Night",
          href: "/destinations/shanghai/what-to-do/bund",
          time: "1h",
          cost: "Free",
          imageSeed: "shanghai-bund-night",
          desc: "The Bund transforms after dark. Pudong's skyline lights up across the river.",
        },
        {
          name: "Xintiandi Dinner",
          href: "/destinations/shanghai/where-to-stay/xintiandi",
          time: "2h",
          cost: "¥150–300",
          imageSeed: "shanghai-xintiandi-dinner",
          desc: "Sleek dining in restored shikumen houses. End the day in style.",
        },
      ],
    },
    {
      dayTitle: "Day 2: Modern Shanghai",
      timeOfDay: "morning",
      items: [
        {
          name: "Shanghai Tower",
          href: "/destinations/shanghai/what-to-do/shanghai-tower",
          time: "1–2h",
          cost: "¥180",
          imageSeed: "shanghai-tower",
          desc: "World's second-tallest building. Observation deck with panoramic views.",
        },
        {
          name: "Jade Buddha Temple",
          href: "/destinations/shanghai/what-to-do",
          time: "1h",
          cost: "¥20",
          imageSeed: "shanghai-jadebuddha",
          desc: "Peaceful temple with two stunning jade Buddha statues.",
        },
      ],
    },
    {
      dayTitle: "Day 2: Modern Shanghai",
      timeOfDay: "afternoon",
      items: [
        {
          name: "Jing'an",
          href: "/destinations/shanghai/where-to-stay/jingan",
          time: "2–3h",
          cost: "Free",
          imageSeed: "shanghai-jingan",
          desc: "Local life, street food, and the beautiful Jing'an Temple.",
        },
        {
          name: "Scallion Noodles",
          href: "/destinations/shanghai/where-to-eat/scallion-oil-noodles",
          time: "45min",
          cost: "¥25–40",
          imageSeed: "scallion-noodles",
          desc: "Simple, fragrant comfort food at a neighborhood shop.",
        },
      ],
    },
    {
      dayTitle: "Day 2: Modern Shanghai",
      timeOfDay: "evening",
      items: [
        {
          name: "Bund Area Nightlife",
          href: "/destinations/shanghai/where-to-stay/bund-area",
          time: "2h+",
          cost: "Varies",
          imageSeed: "shanghai-bund-nightlife",
          desc: "Rooftop bars with skyline views or riverside drinks.",
        },
      ],
    },
  ],
  knowBeforeYouGo: [
    {
      icon: Wifi,
      title: "Internet",
      text: "VPNs required. Download before landing.",
      href: "/china-basics/how-to-get-internet",
    },
    {
      icon: CreditCard,
      title: "Payment",
      text: "Alipay & WeChat Pay dominate. Cash rarely needed.",
      href: "/china-basics/what-apps-to-use/payment",
    },
    {
      icon: TrainFront,
      title: "Transport",
      text: "Metro is excellent. DiDi for taxis.",
      href: "/china-basics/how-to-get-around",
    },
    {
      icon: Smartphone,
      title: "Apps",
      text: "Download Alipay, DiDi, Amap before you go.",
      href: "/china-basics/what-apps-to-use",
    },
    {
      icon: ShieldCheck,
      title: "Visa",
      text: "Most Western nationals: 15–30 day visa-free or e-visa.",
      href: "/china-basics/how-china-differs/visa-guide",
    },
    {
      icon: Thermometer,
      title: "Weather",
      text: "Best time: March–May, September–November.",
      href: "/plan-your-trip/best-time-to-visit",
    },
  ],
  allItems: [
    { id: "bund-attraction", markerId: "bund", name: "The Bund", subtitle: "Shanghai's most iconic waterfront promenade with skyline views.", tag: "Free", imageSeed: "shanghai-bund", href: "/destinations/shanghai/what-to-do/bund", type: "attraction", filters: ["free", "historic", "modern", "nightlife", "landmark"] },
    { id: "yu-garden-attraction", markerId: "yu-garden", name: "Yu Garden", subtitle: "A 400-year-old classical garden surrounded by a lively bazaar.", tag: "¥40", imageSeed: "shanghai-yugarden", href: "/destinations/shanghai/what-to-do/yu-garden", type: "attraction", filters: ["budget", "historic", "family", "landmark"] },
    { id: "french-concession-attraction", markerId: "french-concession", name: "French Concession", subtitle: "Tree-lined avenues, Art Deco villas, and charming cafés.", tag: "Free", imageSeed: "shanghai-frenchconcession", href: "/destinations/shanghai/what-to-do/french-concession", type: "attraction", filters: ["free", "local", "historic", "landmark"] },
    { id: "shanghai-tower-attraction", markerId: "shanghai-tower", name: "Shanghai Tower", subtitle: "The world's second-tallest building with a jaw-dropping observation deck.", tag: "¥180", imageSeed: "shanghai-tower", href: "/destinations/shanghai/what-to-do/shanghai-tower", type: "attraction", filters: ["premium", "modern", "landmark"] },
    { id: "tianzifang-attraction", markerId: "tianzifang", name: "Tianzifang", subtitle: "Winding alleyways packed with studios, galleries, and craft shops.", tag: "Free", imageSeed: "shanghai-tianzifang", href: "/destinations/shanghai/what-to-do", type: "attraction", filters: ["free", "local", "historic"] },
    { id: "jade-buddha-attraction", markerId: "jade-buddha", name: "Jade Buddha Temple", subtitle: "Serene Buddhist temple housing two stunning white jade Buddhas.", tag: "¥20", imageSeed: "shanghai-jadebuddha", href: "/destinations/shanghai/what-to-do", type: "attraction", filters: ["budget", "historic", "landmark"] },
    { id: "xiaolongbao-food", markerId: "xiaolongbao", name: "Xiaolongbao", subtitle: "Shanghai's iconic soup dumplings", tag: "Street Food · ¥30", imageSeed: "xiaolongbao", href: "/destinations/shanghai/where-to-eat/xiaolongbao", type: "food", filters: ["budget", "local", "food"] },
    { id: "shengjianbao-food", markerId: "shengjianbao", name: "Shengjianbao", subtitle: "Pan-fried buns with a crispy bottom", tag: "Street Food · ¥15", imageSeed: "shengjianbao", href: "/destinations/shanghai/where-to-eat/shengjianbao", type: "food", filters: ["budget", "local", "food"] },
    { id: "hairy-crab-food", markerId: "hairy-crab", name: "Hairy Crab", subtitle: "Autumn delicacy from nearby Yangcheng Lake", tag: "Seasonal · ¥200+", imageSeed: "hairy-crab", href: "/destinations/shanghai/where-to-eat/hairy-crab", type: "food", filters: ["premium", "food"] },
    { id: "scallion-noodles-food", markerId: "scallion-oil-noodles", name: "Scallion Oil Noodles", subtitle: "Simple, fragrant, and deeply comforting", tag: "Restaurant · ¥25–40", imageSeed: "scallion-noodles", href: "/destinations/shanghai/where-to-eat/scallion-oil-noodles", type: "food", filters: ["budget", "local", "food"] },
    { id: "bund-area-stay", markerId: "bund", name: "Bund Area", subtitle: "Iconic skyline · Historic architecture · Perfect for first-timers", imageSeed: "shanghai-bund-area", href: "/destinations/shanghai/where-to-stay/bund-area", type: "stay", filters: ["midrange", "historic", "nightlife", "stay"] },
    { id: "french-concession-stay", markerId: "french-concession", name: "French Concession", subtitle: "Cafés & boutiques · Tree-lined streets · Most walkable", imageSeed: "shanghai-french-concession-stay", href: "/destinations/shanghai/where-to-stay/french-concession", type: "stay", filters: ["midrange", "local", "historic", "stay"] },
    { id: "jingan-stay", markerId: "jingan", name: "Jing'an", subtitle: "Local life · Metro hub · Central base", imageSeed: "shanghai-jingan", href: "/destinations/shanghai/where-to-stay/jingan", type: "stay", filters: ["budget", "local", "stay"] },
    { id: "xintiandi-stay", markerId: "xintiandi", name: "Xintiandi", subtitle: "Modern luxury · Nightlife · Sleek dining", imageSeed: "shanghai-xintiandi", href: "/destinations/shanghai/where-to-stay/xintiandi", type: "stay", filters: ["premium", "modern", "nightlife", "stay"] },
    { id: "info-internet", name: "Internet", subtitle: "VPNs required. Download before landing.", imageSeed: "", href: "/china-basics/how-to-get-internet", type: "info", icon: Wifi, filters: ["practical"] },
    { id: "info-payment", name: "Payment", subtitle: "Alipay & WeChat Pay dominate. Cash rarely needed.", imageSeed: "", href: "/china-basics/what-apps-to-use/payment", type: "info", icon: CreditCard, filters: ["practical"] },
    { id: "info-transport", name: "Transport", subtitle: "Metro is excellent. DiDi for taxis.", imageSeed: "", href: "/china-basics/how-to-get-around", type: "info", icon: TrainFront, filters: ["practical"] },
    { id: "info-apps", name: "Apps", subtitle: "Download Alipay, DiDi, Amap before you go.", imageSeed: "", href: "/china-basics/what-apps-to-use", type: "info", icon: Smartphone, filters: ["practical"] },
    { id: "info-visa", name: "Visa", subtitle: "Most Western nationals: 15–30 day visa-free or e-visa.", imageSeed: "", href: "/china-basics/how-china-differs/visa-guide", type: "info", icon: ShieldCheck, filters: ["practical"] },
    { id: "info-weather", name: "Weather", subtitle: "Best time: March–May, September–November.", imageSeed: "", href: "/plan-your-trip/best-time-to-visit", type: "info", icon: Thermometer, filters: ["practical"] },
    { id: "tip-plum-rain", name: "Plum Rain Season", subtitle: "June–July brings muggy, rainy weather. Pack extra socks and a travel umbrella.", imageSeed: "", href: "/destinations/shanghai/local-tips", type: "tip", icon: CloudRain, filters: ["practical"] },
    { id: "tip-taxi", name: "Taxi Pro Tip", subtitle: "Shanghai taxis are cheap, but drivers rarely speak English. Use DiDi with English interface instead.", imageSeed: "", href: "/destinations/shanghai/local-tips", type: "tip", icon: Car, filters: ["practical"] },
    { id: "tip-bund-night", name: "Bund After Dark", subtitle: "The Bund is free and best at night. Skip the overpriced tourist tunnel — walk or take the metro instead.", imageSeed: "", href: "/destinations/shanghai/local-tips", type: "tip", icon: Moon, filters: ["free", "nightlife", "practical"] },
    { id: "tip-metro-maps", name: "Metro & Maps", subtitle: "Metro stops have English signs. Google Maps works with a VPN; Amap is the best local alternative.", imageSeed: "", href: "/destinations/shanghai/local-tips", type: "tip", icon: Map, filters: ["practical"] },
  ],
  footerTitle: "Ready to Explore Shanghai?",
  footerSubtitle:
    "From visa tips to day-by-day itineraries — everything you need for a smooth, unforgettable trip.",
  footerTrustText:
    "Trusted by 1,000+ China travelers · Free itineraries · Local tips",
  footerQuickInfo: [
    {
      icon: Calendar,
      title: "7–14 days recommended",
      description: "Most travelers spend 5–7 days in Shanghai",
    },
    {
      icon: Sun,
      title: "Best time: Mar–May, Sep–Nov",
      description: "Mild weather, fewer crowds",
    },
    {
      icon: Lightbulb,
      title: "First time?",
      description: "Start with our",
      link: { href: "/plan-your-trip/preplanned-trips", label: "7-day route" },
    },
  ],
};
